alpha: 0.4
batch_size_train: 16
batch_size_val: 64
bert_config: configs/config_bert.json
embed_dim: 256
image_res: 256
label_smoothing: 0.0
loss_BIC_wgt: 1
loss_MAC_wgt: 0.1
loss_MLC_wgt: 1
loss_TMG_wgt: 1
loss_bbox_wgt: 0.1
loss_giou_wgt: 0.1
max_words: 50
momentum: 0.995
optimizer: {lr: 2e-05, lr_img: 0.0001, opt: adamW, weight_decay: 0.02}
queue_size: 65536
schedular: {cooldown_epochs: 0, decay_rate: 1, epochs: 50, lr: 2e-05, min_lr: 1e-06,
  sched: cosine, warmup_epochs: 10, warmup_lr: 1e-06}
temp: 0.07
train_file: [/nas/data_2/wanhongz/datasets/DGM4/metadata/train.json]
val_file: [/nas/data_2/wanhongz/datasets/DGM4/metadata/test.json]
vision_width: 768
vocab_size: 30522
